/*
 * jversion.h
 *
 * Copyright (C) 1991-1994, Thomas G. Lane.
 * This file is part of the Independent JPEG Group's software.
 * For conditions of distribution and use, see the accompanying README file.
 *
 * This file contains software version identification.
 */
#if !defined(_JVERSION_H_1999_12_29_11_06)
#define _JVERSION_H_1999_12_29_11_06

#define JVERSION	"5a  7-Dec-94"

#define JCOPYRIGHT	"Copyright (C) 1994, Thomas G. Lane"

#endif//_JVERSION_H_1999_12_29_11_06
